### ISSUE TITLE
Button handling not optimal

### ISSUE THREAD

**Issue by e7p** [Ferdi265/card10-digiclk#2]
I think with the new `BUTTON_UPDATE_TIME` method, it is quite unintiutively handled and sometimes button presses won't get handled. This might need some more investigation, but I really think that prior commit 0ea667e buttons were handled more smooth and without these push misses.

**Comment by Ferdi265** [comment]
I noticed that today morning as well. The reason I added the `BUTTON_UPDATE_TIME` variable and the sleeping was to reduce the time the program was spinning the CPU, and to increase battery lifetime.

The firmware guys are planning to create a callback- / interrupt-based API for buttons sometime in the future, and that would make it much easier to handle button presses accurately while still being energy efficient.

In the meantime, the fix should probably be to identify what the shortest humanly feasible button press time is and adjust the `BUTTON_UPDATE_TIME` accordingly. 100ms was just a wild guess I had.

**Comment by Ferdi265** [comment]
I just noticed today, while trying to calibrate the `BUTTON_UPDATE_TIME` so that it still controls comfortably, that even with a `BUTTON_UPDATE_TIME` of 0, the button handling still lagged.

Logging the render times helped me find the culprit: `monotime.py` wasn't accounting for the fact that `utime.set_time()` floors milliseconds down to 0! After I fixed that everything went smoothly.

The commit fixing this is 2d66191c86a118280cca700b17063ff923d4357e.
